<script src="<?= $baseURL ?>assets/js/jquery-3.3.1.min.js"></script>
<script src="<?= $baseURL ?>assets/js/popper.min.js"></script>
<script src="<?= $baseURL ?>assets/bootstrap/js/bootstrap.min.js"></script>
<script src="<?= $baseURL ?>assets/js/owl.carousel.min.js"></script>
<script src="<?= $baseURL ?>assets/js/sly.min.js"></script>
<script src="<?= $baseURL ?>assets/js/dragscroll.js"></script>
<script src="<?= $baseURL ?>assets/js/jquery.scrollbar.min.js"></script>
<script src="<?= $baseURL ?>assets/js/leaflet.js"></script>
<script src="<?= $baseURL ?>assets/js/leaflet.markercluster.js"></script>
<script src="<?= $baseURL ?>assets/js/custom.js"></script>
<script src="<?= $baseURL ?>assets/js/map-leaflet.js"></script>